[2024-08-05T15:01:39.811+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T15:01:39.867+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: send_stock_data.send_data scheduled__2024-08-05T14:55:00+00:00 [queued]>
[2024-08-05T15:01:39.880+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: send_stock_data.send_data scheduled__2024-08-05T14:55:00+00:00 [queued]>
[2024-08-05T15:01:39.881+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-05T15:01:39.905+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): send_data> on 2024-08-05 14:55:00+00:00
[2024-08-05T15:01:39.915+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1197) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-05T15:01:39.917+0000] {standard_task_runner.py:64} INFO - Started process 1201 to run task
[2024-08-05T15:01:39.915+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'send_stock_data', 'send_data', 'scheduled__2024-08-05T14:55:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/***_stream.py', '--cfg-path', '/tmp/tmp6a_yimfa']
[2024-08-05T15:01:39.918+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask send_data
[2024-08-05T15:01:39.937+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-05T15:01:39.982+0000] {task_command.py:426} INFO - Running <TaskInstance: send_stock_data.send_data scheduled__2024-08-05T14:55:00+00:00 [running]> on host c1646deff093
[2024-08-05T15:01:40.124+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='send_stock_data' AIRFLOW_CTX_TASK_ID='send_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T14:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-05T14:55:00+00:00'
[2024-08-05T15:01:40.126+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T15:01:40.803+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T15:01:40.804+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_stream.py", line 76, in send_data
    for symbol, data_list in formatted_data.items():
                             ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'
[2024-08-05T15:01:40.823+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=send_stock_data, task_id=send_data, run_id=scheduled__2024-08-05T14:55:00+00:00, execution_date=20240805T145500, start_date=20240805T150139, end_date=20240805T150140
[2024-08-05T15:01:40.839+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 30 for task send_data ('list' object has no attribute 'items'; 1201)
[2024-08-05T15:01:40.894+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-05T15:01:40.918+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-05T15:01:40.923+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
