[2024-07-26 07:42:16,326] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: send_stock_data.send_data scheduled__2024-07-26T07:41:00+00:00 [queued]>
[2024-07-26 07:42:16,333] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: send_stock_data.send_data scheduled__2024-07-26T07:41:00+00:00 [queued]>
[2024-07-26 07:42:16,333] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-07-26 07:42:16,334] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2024-07-26 07:42:16,334] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-07-26 07:42:16,346] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): send_data> on 2024-07-26 07:41:00+00:00
[2024-07-26 07:42:16,350] {standard_task_runner.py:52} INFO - Started process 275 to run task
[2024-07-26 07:42:16,352] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_stock_data', 'send_data', 'scheduled__2024-07-26T07:41:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/***_stream.py', '--cfg-path', '/tmp/tmp3_3uuylw', '--error-file', '/tmp/tmpm_pa1eqj']
[2024-07-26 07:42:16,353] {standard_task_runner.py:80} INFO - Job 10: Subtask send_data
[2024-07-26 07:42:16,365] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.10/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-26 07:42:16,401] {task_command.py:371} INFO - Running <TaskInstance: send_stock_data.send_data scheduled__2024-07-26T07:41:00+00:00 [running]> on host a65626265f2c
[2024-07-26 07:42:16,450] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_stock_data
AIRFLOW_CTX_TASK_ID=send_data
AIRFLOW_CTX_EXECUTION_DATE=2024-07-26T07:41:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-26T07:41:00+00:00
[2024-07-26 07:42:20,167] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:42:20,168] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:42:23,904] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:42:23,904] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:42:27,655] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:42:27,656] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:42:31,400] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:42:31,400] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:42:35,163] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:42:35,163] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:42:38,917] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:42:38,918] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:42:42,670] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:42:42,670] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:42:46,439] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:42:46,439] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:42:50,192] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:42:50,192] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:42:53,948] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:42:53,949] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:42:57,699] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:42:57,699] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:43:01,466] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:43:01,467] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:43:05,220] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:43:05,220] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:43:08,982] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:43:08,982] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:43:12,726] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:43:12,726] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:43:16,459] {logging_mixin.py:115} INFO - An error occurred: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2024-07-26 07:43:16,460] {kafka.py:483} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2024-07-26 07:43:16,464] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:43:16,464] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:43:16,464] {python.py:173} INFO - Done. Returned value was: None
[2024-07-26 07:43:16,473] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=send_stock_data, task_id=send_data, execution_date=20240726T074100, start_date=20240726T074216, end_date=20240726T074316
[2024-07-26 07:43:16,504] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-07-26 07:43:16,522] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-26 07:43:16,535] {dagrun.py:564} INFO - Marking run <DagRun send_stock_data @ 2024-07-26 07:41:00+00:00: scheduled__2024-07-26T07:41:00+00:00, externally triggered: False> successful
[2024-07-26 07:43:16,536] {dagrun.py:609} INFO - DagRun Finished: dag_id=send_stock_data, execution_date=2024-07-26 07:41:00+00:00, run_id=scheduled__2024-07-26T07:41:00+00:00, run_start_date=2024-07-26 07:42:13.398478+00:00, run_end_date=2024-07-26 07:43:16.536297+00:00, run_duration=63.137819, state=success, external_trigger=False, run_type=scheduled, data_interval_start=2024-07-26 07:41:00+00:00, data_interval_end=2024-07-26 07:42:00+00:00, dag_hash=0dd8dee774410ef67658687eadd5a515
