[2024-07-25 18:17:03,798] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T18:16:00+00:00 [queued]>
[2024-07-25 18:17:03,805] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T18:16:00+00:00 [queued]>
[2024-07-25 18:17:03,805] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-07-25 18:17:03,805] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2024-07-25 18:17:03,805] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-07-25 18:17:03,818] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): send_data> on 2024-07-25 18:16:00+00:00
[2024-07-25 18:17:03,822] {standard_task_runner.py:52} INFO - Started process 1217 to run task
[2024-07-25 18:17:03,824] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_stock_data', 'send_data', 'scheduled__2024-07-25T18:16:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/***_stream.py', '--cfg-path', '/tmp/tmpgzzfokey', '--error-file', '/tmp/tmpo8polq5h']
[2024-07-25 18:17:03,825] {standard_task_runner.py:80} INFO - Job 54: Subtask send_data
[2024-07-25 18:17:03,837] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.10/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-25 18:17:03,876] {task_command.py:371} INFO - Running <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T18:16:00+00:00 [running]> on host 3375e7ece4d4
[2024-07-25 18:17:03,929] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_stock_data
AIRFLOW_CTX_TASK_ID=send_data
AIRFLOW_CTX_EXECUTION_DATE=2024-07-25T18:16:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-25T18:16:00+00:00
[2024-07-25 18:17:07,671] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:17:07,671] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:17:11,441] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:17:11,441] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:17:15,215] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:17:15,215] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:17:18,977] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:17:18,977] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:17:22,703] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:17:22,703] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:17:26,434] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:17:26,434] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:17:30,179] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:17:30,179] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:17:33,946] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:17:33,947] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:17:37,716] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:17:37,716] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:17:41,478] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:17:41,479] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:17:45,237] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:17:45,237] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:17:48,996] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:17:48,996] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:17:52,753] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:17:52,753] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:17:56,513] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:17:56,514] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:18:00,274] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:18:00,274] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:18:03,937] {logging_mixin.py:115} INFO - An error occurred: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2024-07-25 18:18:03,938] {kafka.py:483} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2024-07-25 18:18:04,016] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:18:04,017] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:18:04,017] {python.py:173} INFO - Done. Returned value was: None
[2024-07-25 18:18:04,026] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=send_stock_data, task_id=send_data, execution_date=20240725T181600, start_date=20240725T181703, end_date=20240725T181804
[2024-07-25 18:18:04,063] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-07-25 18:18:04,081] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25 18:18:04,094] {dagrun.py:564} INFO - Marking run <DagRun send_stock_data @ 2024-07-25 18:16:00+00:00: scheduled__2024-07-25T18:16:00+00:00, externally triggered: False> successful
[2024-07-25 18:18:04,095] {dagrun.py:609} INFO - DagRun Finished: dag_id=send_stock_data, execution_date=2024-07-25 18:16:00+00:00, run_id=scheduled__2024-07-25T18:16:00+00:00, run_start_date=2024-07-25 18:17:00.579268+00:00, run_end_date=2024-07-25 18:18:04.095192+00:00, run_duration=63.515924, state=success, external_trigger=False, run_type=scheduled, data_interval_start=2024-07-25 18:16:00+00:00, data_interval_end=2024-07-25 18:17:00+00:00, dag_hash=0dd8dee774410ef67658687eadd5a515
