[2024-07-25 18:41:03,736] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T18:40:00+00:00 [queued]>
[2024-07-25 18:41:03,742] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T18:40:00+00:00 [queued]>
[2024-07-25 18:41:03,743] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-07-25 18:41:03,743] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2024-07-25 18:41:03,743] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-07-25 18:41:03,755] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): send_data> on 2024-07-25 18:40:00+00:00
[2024-07-25 18:41:03,759] {standard_task_runner.py:52} INFO - Started process 1775 to run task
[2024-07-25 18:41:03,761] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_stock_data', 'send_data', 'scheduled__2024-07-25T18:40:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/***_stream.py', '--cfg-path', '/tmp/tmp5g_elmzz', '--error-file', '/tmp/tmpk23d_r2e']
[2024-07-25 18:41:03,761] {standard_task_runner.py:80} INFO - Job 81: Subtask send_data
[2024-07-25 18:41:03,773] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.10/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-25 18:41:03,807] {task_command.py:371} INFO - Running <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T18:40:00+00:00 [running]> on host 3375e7ece4d4
[2024-07-25 18:41:03,858] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_stock_data
AIRFLOW_CTX_TASK_ID=send_data
AIRFLOW_CTX_EXECUTION_DATE=2024-07-25T18:40:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-25T18:40:00+00:00
[2024-07-25 18:41:07,572] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:41:07,573] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:41:11,335] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:41:11,335] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:41:15,089] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:41:15,089] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:41:18,843] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:41:18,844] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:41:22,583] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:41:22,583] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:41:26,326] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:41:26,327] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:41:30,090] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:41:30,090] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:41:33,857] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:41:33,858] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:41:37,604] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:41:37,605] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:41:41,358] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:41:41,359] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:41:45,135] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:41:45,135] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:41:48,875] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:41:48,875] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:41:52,643] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:41:52,643] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:41:56,390] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:41:56,390] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:42:00,139] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:42:00,139] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:42:03,869] {logging_mixin.py:115} INFO - An error occurred: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2024-07-25 18:42:03,870] {kafka.py:483} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2024-07-25 18:42:03,897] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:42:03,897] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:42:03,898] {python.py:173} INFO - Done. Returned value was: None
[2024-07-25 18:42:03,907] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=send_stock_data, task_id=send_data, execution_date=20240725T184000, start_date=20240725T184103, end_date=20240725T184203
[2024-07-25 18:42:03,934] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-07-25 18:42:03,953] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25 18:42:03,965] {dagrun.py:564} INFO - Marking run <DagRun send_stock_data @ 2024-07-25 18:40:00+00:00: scheduled__2024-07-25T18:40:00+00:00, externally triggered: False> successful
[2024-07-25 18:42:03,966] {dagrun.py:609} INFO - DagRun Finished: dag_id=send_stock_data, execution_date=2024-07-25 18:40:00+00:00, run_id=scheduled__2024-07-25T18:40:00+00:00, run_start_date=2024-07-25 18:41:00.910546+00:00, run_end_date=2024-07-25 18:42:03.966205+00:00, run_duration=63.055659, state=success, external_trigger=False, run_type=scheduled, data_interval_start=2024-07-25 18:40:00+00:00, data_interval_end=2024-07-25 18:41:00+00:00, dag_hash=0dd8dee774410ef67658687eadd5a515
