[2024-07-30T08:50:00.307+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-30T08:50:00.357+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: send_stock_data.get_data scheduled__2024-07-30T08:45:00+00:00 [queued]>
[2024-07-30T08:50:00.367+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: send_stock_data.get_data scheduled__2024-07-30T08:45:00+00:00 [queued]>
[2024-07-30T08:50:00.367+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-30T08:50:00.383+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_data> on 2024-07-30 08:45:00+00:00
[2024-07-30T08:50:00.392+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=340) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-30T08:50:00.392+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'send_stock_data', 'get_data', 'scheduled__2024-07-30T08:45:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/***_stream.py', '--cfg-path', '/tmp/tmp_c83t18g']
[2024-07-30T08:50:00.393+0000] {standard_task_runner.py:64} INFO - Started process 341 to run task
[2024-07-30T08:50:00.394+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask get_data
[2024-07-30T08:50:00.410+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-30T08:50:00.447+0000] {task_command.py:426} INFO - Running <TaskInstance: send_stock_data.get_data scheduled__2024-07-30T08:45:00+00:00 [running]> on host 2c5d54a8b113
[2024-07-30T08:50:00.543+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='send_stock_data' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-30T08:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-30T08:45:00+00:00'
[2024-07-30T08:50:00.544+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-30T08:50:00.553+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-30T08:50:00.554+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_data() missing 1 required positional argument: 'list'
[2024-07-30T08:50:00.566+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=send_stock_data, task_id=get_data, run_id=scheduled__2024-07-30T08:45:00+00:00, execution_date=20240730T084500, start_date=20240730T085000, end_date=20240730T085000
[2024-07-30T08:50:00.580+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 34 for task get_data (get_data() missing 1 required positional argument: 'list'; 341)
[2024-07-30T08:50:00.608+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-30T08:50:00.633+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-30T08:50:00.640+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
