[2024-07-26 07:56:27,053] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: send_stock_data.send_data scheduled__2024-07-26T07:55:00+00:00 [queued]>
[2024-07-26 07:56:27,061] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: send_stock_data.send_data scheduled__2024-07-26T07:55:00+00:00 [queued]>
[2024-07-26 07:56:27,062] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-07-26 07:56:27,062] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2024-07-26 07:56:27,062] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-07-26 07:56:27,073] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): send_data> on 2024-07-26 07:55:00+00:00
[2024-07-26 07:56:27,076] {standard_task_runner.py:52} INFO - Started process 574 to run task
[2024-07-26 07:56:27,079] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_stock_data', 'send_data', 'scheduled__2024-07-26T07:55:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/***_stream.py', '--cfg-path', '/tmp/tmptnm4xnkg', '--error-file', '/tmp/tmpfzd_26el']
[2024-07-26 07:56:27,080] {standard_task_runner.py:80} INFO - Job 16: Subtask send_data
[2024-07-26 07:56:27,093] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.10/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-26 07:56:27,127] {task_command.py:371} INFO - Running <TaskInstance: send_stock_data.send_data scheduled__2024-07-26T07:55:00+00:00 [running]> on host a65626265f2c
[2024-07-26 07:56:27,176] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_stock_data
AIRFLOW_CTX_TASK_ID=send_data
AIRFLOW_CTX_EXECUTION_DATE=2024-07-26T07:55:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-26T07:55:00+00:00
[2024-07-26 07:56:30,872] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:56:30,872] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:56:34,600] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:56:34,600] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:56:38,350] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:56:38,350] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:56:42,088] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:56:42,088] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:56:45,824] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:56:45,825] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:56:49,577] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:56:49,577] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:56:53,314] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:56:53,314] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:56:57,086] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:56:57,086] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:57:00,862] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:57:00,862] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:57:04,602] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:57:04,617] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:57:08,376] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:57:08,377] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:57:12,129] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:57:12,129] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:57:15,885] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:57:15,885] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:57:19,636] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:57:19,636] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:57:23,373] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:57:23,374] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:57:27,138] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:57:27,139] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:57:27,185] {logging_mixin.py:115} INFO - An error occurred: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2024-07-26 07:57:27,186] {kafka.py:483} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2024-07-26 07:57:30,868] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-26 07:57:30,868] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-07-26 07:57:30,869] {python.py:173} INFO - Done. Returned value was: None
[2024-07-26 07:57:30,877] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=send_stock_data, task_id=send_data, execution_date=20240726T075500, start_date=20240726T075627, end_date=20240726T075730
[2024-07-26 07:57:30,907] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-07-26 07:57:30,925] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-26 07:57:30,939] {dagrun.py:564} INFO - Marking run <DagRun send_stock_data @ 2024-07-26 07:55:00+00:00: scheduled__2024-07-26T07:55:00+00:00, externally triggered: False> successful
[2024-07-26 07:57:30,940] {dagrun.py:609} INFO - DagRun Finished: dag_id=send_stock_data, execution_date=2024-07-26 07:55:00+00:00, run_id=scheduled__2024-07-26T07:55:00+00:00, run_start_date=2024-07-26 07:56:23.853833+00:00, run_end_date=2024-07-26 07:57:30.939985+00:00, run_duration=67.086152, state=success, external_trigger=False, run_type=scheduled, data_interval_start=2024-07-26 07:55:00+00:00, data_interval_end=2024-07-26 07:56:00+00:00, dag_hash=0dd8dee774410ef67658687eadd5a515
