[2024-07-25 17:41:43,669] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T17:40:00+00:00 [queued]>
[2024-07-25 17:41:43,675] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T17:40:00+00:00 [queued]>
[2024-07-25 17:41:43,675] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-07-25 17:41:43,675] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2024-07-25 17:41:43,676] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-07-25 17:41:43,687] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): send_data> on 2024-07-25 17:40:00+00:00
[2024-07-25 17:41:43,691] {standard_task_runner.py:52} INFO - Started process 435 to run task
[2024-07-25 17:41:43,693] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_stock_data', 'send_data', 'scheduled__2024-07-25T17:40:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/***_stream.py', '--cfg-path', '/tmp/tmpjth8mmmg', '--error-file', '/tmp/tmp_uh7xbus']
[2024-07-25 17:41:43,694] {standard_task_runner.py:80} INFO - Job 18: Subtask send_data
[2024-07-25 17:41:43,705] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.10/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-25 17:41:43,739] {task_command.py:371} INFO - Running <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T17:40:00+00:00 [running]> on host 3375e7ece4d4
[2024-07-25 17:41:43,785] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_stock_data
AIRFLOW_CTX_TASK_ID=send_data
AIRFLOW_CTX_EXECUTION_DATE=2024-07-25T17:40:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-25T17:40:00+00:00
[2024-07-25 17:41:43,787] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-07-25 17:41:43,787] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-07-25 17:41:43,788] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-07-25 17:41:43,788] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-07-25 17:41:43,837] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-07-25 17:41:43,837] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-07-25 17:41:43,838] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-07-25 17:41:43,887] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-07-25 17:41:43,887] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-07-25 17:41:43,888] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-07-25 17:41:43,888] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow_stream.py", line 38, in send_data
    producer = KafkaProducer(
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-07-25 17:41:43,897] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=send_stock_data, task_id=send_data, execution_date=20240725T174000, start_date=20240725T174143, end_date=20240725T174143
[2024-07-25 17:41:43,906] {standard_task_runner.py:92} ERROR - Failed to execute job 18 for task send_data (NoBrokersAvailable; 435)
[2024-07-25 17:41:43,945] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-07-25 17:41:43,969] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
