[2024-07-25 18:34:12,080] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T18:32:00+00:00 [queued]>
[2024-07-25 18:34:12,087] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T18:32:00+00:00 [queued]>
[2024-07-25 18:34:12,087] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-07-25 18:34:12,087] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2024-07-25 18:34:12,087] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-07-25 18:34:12,102] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): send_data> on 2024-07-25 18:32:00+00:00
[2024-07-25 18:34:12,106] {standard_task_runner.py:52} INFO - Started process 1612 to run task
[2024-07-25 18:34:12,108] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_stock_data', 'send_data', 'scheduled__2024-07-25T18:32:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/***_stream.py', '--cfg-path', '/tmp/tmprnzdv0fq', '--error-file', '/tmp/tmpzgatvrbi']
[2024-07-25 18:34:12,109] {standard_task_runner.py:80} INFO - Job 71: Subtask send_data
[2024-07-25 18:34:12,123] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.10/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-25 18:34:12,164] {task_command.py:371} INFO - Running <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T18:32:00+00:00 [running]> on host 3375e7ece4d4
[2024-07-25 18:34:12,220] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_stock_data
AIRFLOW_CTX_TASK_ID=send_data
AIRFLOW_CTX_EXECUTION_DATE=2024-07-25T18:32:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-25T18:32:00+00:00
[2024-07-25 18:34:15,921] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:34:15,921] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:34:19,686] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:34:19,686] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:34:23,443] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:34:23,443] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:34:27,206] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:34:27,206] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:34:30,954] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:34:30,954] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:34:34,707] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:34:34,707] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:34:38,458] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:34:38,459] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:34:42,228] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:34:42,228] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:34:45,983] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:34:45,984] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:34:49,729] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:34:49,729] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:34:53,489] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:34:53,490] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:34:57,255] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:34:57,255] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:35:01,011] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:35:01,012] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:35:04,767] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:35:04,768] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:35:08,535] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:35:08,535] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:35:12,232] {logging_mixin.py:115} INFO - An error occurred: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2024-07-25 18:35:12,232] {kafka.py:483} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2024-07-25 18:35:12,289] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:35:12,290] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:35:12,290] {python.py:173} INFO - Done. Returned value was: None
[2024-07-25 18:35:12,301] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=send_stock_data, task_id=send_data, execution_date=20240725T183200, start_date=20240725T183412, end_date=20240725T183512
[2024-07-25 18:35:12,342] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-07-25 18:35:12,362] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25 18:35:12,378] {dagrun.py:564} INFO - Marking run <DagRun send_stock_data @ 2024-07-25 18:32:00+00:00: scheduled__2024-07-25T18:32:00+00:00, externally triggered: False> successful
[2024-07-25 18:35:12,378] {dagrun.py:609} INFO - DagRun Finished: dag_id=send_stock_data, execution_date=2024-07-25 18:32:00+00:00, run_id=scheduled__2024-07-25T18:32:00+00:00, run_start_date=2024-07-25 18:34:08.595113+00:00, run_end_date=2024-07-25 18:35:12.378899+00:00, run_duration=63.783786, state=success, external_trigger=False, run_type=scheduled, data_interval_start=2024-07-25 18:32:00+00:00, data_interval_end=2024-07-25 18:33:00+00:00, dag_hash=0dd8dee774410ef67658687eadd5a515
