[2024-07-25 18:25:03,722] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T18:24:00+00:00 [queued]>
[2024-07-25 18:25:03,732] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T18:24:00+00:00 [queued]>
[2024-07-25 18:25:03,732] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-07-25 18:25:03,732] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2024-07-25 18:25:03,732] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-07-25 18:25:03,746] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): send_data> on 2024-07-25 18:24:00+00:00
[2024-07-25 18:25:03,750] {standard_task_runner.py:52} INFO - Started process 1391 to run task
[2024-07-25 18:25:03,753] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_stock_data', 'send_data', 'scheduled__2024-07-25T18:24:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/***_stream.py', '--cfg-path', '/tmp/tmplu4xz8mt', '--error-file', '/tmp/tmpl4ikefbb']
[2024-07-25 18:25:03,754] {standard_task_runner.py:80} INFO - Job 60: Subtask send_data
[2024-07-25 18:25:03,767] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.10/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-25 18:25:03,812] {task_command.py:371} INFO - Running <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T18:24:00+00:00 [running]> on host 3375e7ece4d4
[2024-07-25 18:25:03,874] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_stock_data
AIRFLOW_CTX_TASK_ID=send_data
AIRFLOW_CTX_EXECUTION_DATE=2024-07-25T18:24:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-25T18:24:00+00:00
[2024-07-25 18:25:07,582] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:25:07,583] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:25:11,325] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:25:11,326] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:25:15,094] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:25:15,095] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:25:18,848] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:25:18,849] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:25:22,617] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:25:22,618] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:25:26,357] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:25:26,358] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:25:30,097] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:25:30,097] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:25:33,855] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:25:33,855] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:25:37,614] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:25:37,614] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:25:41,366] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:25:41,367] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:25:45,122] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:25:45,122] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:25:48,880] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:25:48,880] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:25:52,638] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:25:52,638] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:25:56,401] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:25:56,402] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:26:00,151] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:26:00,152] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:26:03,883] {logging_mixin.py:115} INFO - An error occurred: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2024-07-25 18:26:03,884] {kafka.py:483} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2024-07-25 18:26:03,913] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-07-25 18:26:03,914] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2024-07-25 18:26:03,914] {python.py:173} INFO - Done. Returned value was: None
[2024-07-25 18:26:03,923] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=send_stock_data, task_id=send_data, execution_date=20240725T182400, start_date=20240725T182503, end_date=20240725T182603
[2024-07-25 18:26:03,956] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-07-25 18:26:03,976] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25 18:26:03,990] {dagrun.py:564} INFO - Marking run <DagRun send_stock_data @ 2024-07-25 18:24:00+00:00: scheduled__2024-07-25T18:24:00+00:00, externally triggered: False> successful
[2024-07-25 18:26:03,991] {dagrun.py:609} INFO - DagRun Finished: dag_id=send_stock_data, execution_date=2024-07-25 18:24:00+00:00, run_id=scheduled__2024-07-25T18:24:00+00:00, run_start_date=2024-07-25 18:25:00.836205+00:00, run_end_date=2024-07-25 18:26:03.991519+00:00, run_duration=63.155314, state=success, external_trigger=False, run_type=scheduled, data_interval_start=2024-07-25 18:24:00+00:00, data_interval_end=2024-07-25 18:25:00+00:00, dag_hash=0dd8dee774410ef67658687eadd5a515
